# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://aviadr1.github.io/learn-python/"

git_url = "https://github.com/aviadr1/learn-python/tree/master/"

def custom_doc_links(name): return None
